import type { CustomerReview, Pharmacy, Product } from './types';

export const demoProducts: Product[] = [
  {
    _id: 'demo-aspirin',
    name: 'Aspirin',
    photo: 'https://i.ibb.co/bLKP624/5-15-1000x1000-min.jpg',
    supplier: 'Square',
    brand: 'Square',
    stock: 12,
    price: 89.66,
    category: 'Medicine',
    discount: 70,
    rating: 4.8,
    description:
      'A trusted everyday medicine. Always follow the package instructions and consult a healthcare professional when necessary.',
  },
  {
    _id: 'demo-paracetamol',
    name: 'Paracetamol',
    photo: 'https://i.ibb.co/Hg0zZkQ/shop-4-7-1000x1000-min.jpg',
    supplier: 'Acme',
    brand: 'Acme',
    stock: 19,
    price: 34.16,
    category: 'Heart',
    discount: 0,
    rating: 4.6,
  },
  {
    _id: 'demo-ibuprofen',
    name: 'Ibuprofen',
    photo: 'https://i.ibb.co/02WmJdc/5-19-1000x1000-min.jpg',
    supplier: 'Beximco',
    brand: 'Beximco',
    stock: 9,
    price: 53.76,
    category: 'Head',
    discount: 35,
    rating: 4.7,
  },
  {
    _id: 'demo-acetaminophen',
    name: 'Acetaminophen',
    photo: 'https://i.ibb.co/GxTVSVk/shop-4-9-1000x1000-min.jpg',
    supplier: 'ACI',
    brand: 'ACI',
    stock: 14,
    price: 28.57,
    category: 'Hand',
    discount: 0,
    rating: 4.9,
  },
  {
    _id: 'demo-naproxen',
    name: 'Naproxen',
    photo: 'https://i.ibb.co/X330FTj/shop-4-10-1000x1000-min.jpg',
    supplier: 'Uniliver',
    brand: 'Uniliver',
    stock: 10,
    price: 56.34,
    category: 'Leg',
    discount: 0,
    rating: 4.5,
  },
  {
    _id: 'demo-amoxicillin',
    name: 'Amoxicillin',
    photo: 'https://i.ibb.co/bLKP624/5-15-1000x1000-min.jpg',
    supplier: 'Square',
    brand: 'Square',
    stock: 25,
    price: 45.99,
    category: 'Medicine',
    discount: 0,
    rating: 4.4,
  },
];

export const demoPharmacies: Pharmacy[] = [
  {
    _id: 'demo-wellness',
    name: 'Wellness Pharma',
    address: 'Reitarska St, 17',
    city: 'Kyiv',
    phone: '045-256-9564',
    rating: 4.8,
    status: 'OPEN',
  },
  {
    _id: 'demo-family',
    name: 'Family Drugstore',
    address: 'Petra Sahaidachnoho St, 32',
    city: 'Kyiv',
    phone: '045-416-3199',
    rating: 4.6,
    status: 'OPEN',
  },
  {
    _id: 'demo-bright',
    name: 'Bright Health Pharmacy',
    address: 'Mezhyhirska St, 17',
    city: 'Kyiv',
    phone: '050-858-9718',
    rating: 4.7,
    status: 'OPEN',
  },
  {
    _id: 'demo-hope',
    name: 'Pharmacy Hope',
    address: 'Shevchenka St, 100',
    city: 'Lviv',
    phone: '0322-45-67-89',
    rating: 4.4,
    status: 'OPEN',
  },
  {
    _id: 'demo-aesculap',
    name: 'Aesculap',
    address: 'Peace Ave, 5',
    city: 'Dnipro',
    phone: '056-744-55-66',
    rating: 4.9,
    status: 'OPEN',
  },
  {
    _id: 'demo-pharmakor',
    name: 'Pharmakor',
    address: 'Hoholia St, 24',
    city: 'Kharkiv',
    phone: '0572-58-22-12',
    rating: 4.2,
    status: 'CLOSE',
  },
];

export const demoReviews: CustomerReview[] = [
  {
    _id: 'review-maria',
    name: 'Maria Tkachuk',
    testimonial:
      'The ordering process was clear and quick. I found everything I needed and the whole experience felt friendly and reliable.',
  },
  {
    _id: 'review-sergey',
    name: 'Sergey Rybachok',
    testimonial:
      'A very convenient way to browse medicines and find a nearby pharmacy. The interface is simple and easy to understand.',
  },
  {
    _id: 'review-natalia',
    name: 'Natalia Chatuk',
    testimonial:
      'I liked how fast it was to compare products, add them to my cart and see all order details in one place.',
  },
];
